### ISSUE TITLE
XCTestWD : TextField element that cannot be selected

### ISSUE THREAD

**Issue by aloneszjl** [alibaba/macaca#971] opened 2020-04-16 02:30 UTC
* **Macaca Version**:
2.2.0
* **Macaca Doctor Logs**:
```
  node version: v12.8.1

  iOS checklist:

  macOS version: 10.15.4
  Xcode Command Line Tools is ready, version: 2373.
  xcodebuild version: 11.4
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
```
* **Operate System**:
macOS
macaca-ios: 2.1.0
XCTestWD version: 1.4.24
* **Programming Language**:
javascript

* **Problem**:
The second call to the text field method fails to focus on the element

![image](https://user-images.githubusercontent.com/19307426/79407957-c6960d80-7fcc-11ea-8ef6-08e85b45113d.png)

**Comment by paradite** [comment] 2020-04-18 11:06
@aloneszjl actually i managed to solve this issue by deleting the `iPhone 8` simulator and reinstalling it again inside Xcode 11.4. Can you try to see if this resolves the issue?

**Comment by paradite** [comment] 2020-04-25 02:52
closed as the issue is confirmed fixed.

**Closed by paradite** 2020-04-25 02:52 UTC
Labels: iOS, waiting for response
